site_name: Klipper-Backup
site_url: https://staubgeborener.github.io/klipper-backup/
site_description: "Klipper backup script for manual or automated GitHub backups. Lightweight, pragmatic and comfortable"

repo_url: https://github.com/staubgeborener/klipper-backup/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Configuration: configuration.md
      - Updates: updates.md
      - Execute: execute.md
  - Addition:
      - TL;DR: tldr.md
      - Migration: migration.md
