# .github/workflows/markdown_issue_check.yml
name: Check for Markdown code blocks in Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write # Needed to post comments

jobs:
  check_markdown:
    runs-on: ubuntu-latest
    name: Markdown issue check

    steps:
    - name: Check for Markdown code usage
      id: check_markdown # Give the step an ID to reference its outputs
      run: |
        ISSUE_BODY="${{ github.event.issue.body }}"

        # Check if the issue body contains Markdown inline code or code block (`)
        # Use grep -q for quiet mode (no output, just exit status)
        if echo "$ISSUE_BODY" | grep -q "`"; then
          echo "Markdown code detected."
          # Set step output using the recommended GITHUB_OUTPUT file
          echo "markdown_used=true" >> $GITHUB_OUTPUT
        else
          echo "No Markdown code detected."
          # Set step output using the recommended GITHUB_OUTPUT file
          echo "markdown_used=false" >> $GITHUB_OUTPUT
        fi

    - name: Comment on the issue if no Markdown code is detected
      # Correctly reference the output from the 'check_markdown' step
      if: steps.check_markdown.outputs.markdown_used == 'false'
      env:
        # Provide GITHUB_TOKEN to the gh command
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Get issue number from the event payload
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: |
        # Define the comment body using a heredoc for readability
        # Use GitHub markdown within the comment itself
        COMMENT_BODY=$(cat <<'EOF'
        Please use Markdown syntax (&#96;&#96;) for code snippets and log files in your issue. You may have confirmed the checkbox stating you used Markdown, but none was automatically recognized in your post.

        Using Markdown makes your issue significantly more readable and helps others find a solution to your problem more quickly.

        **Examples:**

        *   The backtick symbol (&#96;) around text like &#96;code&#96; turns it into inline `code`.
        *   For longer code blocks or log files, use three backticks (&#96;&#96;&#96;) on lines before and after the content:

            &#96;&#96;&#96;
            # Your multi-line
            # code or log
            # goes here
            &#96;&#96;&#96;

            This will render like:
            ```
            # Your multi-line
            # code or log
            # goes here
            ```

        Please **edit your issue** to incorporate Markdown formatting for any code or log excerpts. If you believe this message was sent in error, please disregard it. Thank you!
        EOF
        )

        # Use GitHub CLI to add a comment - it handles quoting and API calls correctly
        gh issue comment "$ISSUE_NUMBER" --body "$COMMENT_BODY"



